import assert from 'node:assert/strict';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { loadEngineContext, listLibraries } from '../src/shared/engine-context.ts';
import { routeHarvestPlan, routeScheduleConfig } from '../src/cli/routes.ts';
import { configurationFiles } from '../src/shared/config-files.ts';
import { asLibraryId } from '../src/shared/identity.ts';
import { evaluateCandidate } from '../src/library/selection/paper-policy.ts';
import type { PaperMetadata } from '../src/types/papers.ts';
import { withPostTrainingFixture } from './helpers/llm-post-training-fixture.ts';

const libraryId = asLibraryId('llm-post-training');
const expectedTracks = ['pt-foundations','pt-sft','pt-data-curation','pt-synthetic-data','pt-reward-modeling','pt-preference-optimization','pt-policy-optimization','pt-verifiable-rewards','pt-reasoning','pt-distillation','pt-tool-agent','pt-multimodal','pt-safety-alignment','pt-adaptation','pt-efficient-tuning','pt-training-systems','pt-stability','pt-evaluation'];
const expectedQueryContract = [
  { id: 'pt-foundations', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"post-training\" OR ti:\"post training\" OR ti:\"posttraining\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-sft', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"instruction tuning\" OR abs:\"instruction tuning\" OR ti:\"supervised fine-tuning\" OR abs:\"supervised fine-tuning\" OR ti:\"supervised finetuning\" OR abs:\"supervised finetuning\" OR ti:\"SFT\" OR abs:\"SFT\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-data-curation', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"instruction data\" OR abs:\"instruction data\" OR ti:\"preference data\" OR abs:\"preference data\" OR ti:\"post-training data\" OR abs:\"post-training data\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-synthetic-data', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"synthetic instruction\" OR abs:\"synthetic instruction\" OR ti:\"synthetic preference\" OR abs:\"synthetic preference\" OR ti:\"self-instruct\" OR abs:\"self-instruct\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-reward-modeling', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"reward model\" OR abs:\"reward model\" OR ti:\"reward models\" OR abs:\"reward models\" OR ti:\"reward modeling\" OR abs:\"reward modeling\" OR ti:\"process supervision\" OR abs:\"process supervision\" OR ti:\"verifier training\" OR abs:\"verifier training\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-preference-optimization', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"preference optimization\" OR abs:\"preference optimization\" OR ti:\"preference optimisation\" OR abs:\"preference optimisation\" OR ti:\"DPO\" OR abs:\"DPO\" OR ti:\"ORPO\" OR abs:\"ORPO\" OR ti:\"SimPO\" OR abs:\"SimPO\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-policy-optimization', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"PPO\" OR abs:\"PPO\" OR ti:\"GRPO\" OR abs:\"GRPO\" OR ti:\"policy optimization\" OR abs:\"policy optimization\" OR ti:\"policy optimisation\" OR abs:\"policy optimisation\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-verifiable-rewards', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"verifiable reward\" OR abs:\"verifiable reward\" OR ti:\"verifiable rewards\" OR abs:\"verifiable rewards\" OR ti:\"RLVR\" OR abs:\"RLVR\" OR ti:\"rule-based reward\" OR abs:\"rule-based reward\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-reasoning', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"reasoning training\" OR abs:\"reasoning training\" OR ti:\"reasoning distillation\" OR abs:\"reasoning distillation\" OR ti:\"reasoning reinforcement learning\" OR abs:\"reasoning reinforcement learning\" OR ti:\"reasoning post-training\" OR abs:\"reasoning post-training\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-distillation', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"distillation\" OR abs:\"distillation\" OR ti:\"knowledge distillation\" OR abs:\"knowledge distillation\" OR ti:\"policy distillation\" OR abs:\"policy distillation\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-tool-agent', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"agent reinforcement learning\" OR abs:\"agent reinforcement learning\" OR ti:\"agent training\" OR abs:\"agent training\" OR ti:\"tool-use training\" OR abs:\"tool-use training\" OR ti:\"trajectory supervision\" OR abs:\"trajectory supervision\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-multimodal', query: "(ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\" OR ti:\"multimodal language models\" OR abs:\"multimodal language models\" OR ti:\"audio language model\" OR abs:\"audio language model\" OR ti:\"video language model\" OR abs:\"video language model\") AND (ti:\"instruction tuning\" OR abs:\"instruction tuning\" OR ti:\"vision-language alignment\" OR abs:\"vision-language alignment\" OR ti:\"reinforcement learning\" OR abs:\"reinforcement learning\" OR ti:\"post-training\" OR abs:\"post-training\" OR ti:\"post training\" OR abs:\"post training\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-safety-alignment', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"safety alignment\" OR abs:\"safety alignment\" OR ti:\"safety fine-tuning\" OR abs:\"safety fine-tuning\" OR ti:\"RLHF\" OR ti:\"RLAIF\" OR abs:\"RLAIF\" OR ti:\"constitutional AI\" OR abs:\"constitutional AI\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-adaptation', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"continual fine-tuning\" OR abs:\"continual fine-tuning\" OR ti:\"continual finetuning\" OR abs:\"continual finetuning\" OR ti:\"domain instruction tuning\" OR abs:\"domain instruction tuning\" OR ti:\"multilingual instruction tuning\" OR abs:\"multilingual instruction tuning\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-efficient-tuning', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"LoRA\" OR abs:\"LoRA\" OR ti:\"QLoRA\" OR abs:\"QLoRA\" OR ti:\"parameter-efficient fine-tuning\" OR abs:\"parameter-efficient fine-tuning\" OR ti:\"parameter efficient finetuning\" OR abs:\"parameter efficient finetuning\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-training-systems', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"RLHF\" OR abs:\"RLHF\" OR ti:\"GRPO\" OR abs:\"GRPO\" OR ti:\"post-training system\" OR abs:\"post-training system\" OR ti:\"post-training systems\" OR abs:\"post-training systems\" OR ti:\"asynchronous reinforcement learning\" OR abs:\"asynchronous reinforcement learning\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-stability', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"post-training stability\" OR abs:\"post-training stability\" OR ti:\"reward hacking\" OR abs:\"reward hacking\" OR ti:\"entropy collapse\" OR abs:\"entropy collapse\" OR ti:\"preference optimization\" OR abs:\"preference optimization\")", dateModes: ['submitted', 'updated'] },
  { id: 'pt-evaluation', query: "(ti:\"language model\" OR abs:\"language model\" OR ti:\"language models\" OR abs:\"language models\" OR ti:\"LLM\" OR abs:\"LLM\" OR ti:\"LLMs\" OR abs:\"LLMs\" OR ti:\"vision-language model\" OR abs:\"vision-language model\" OR ti:\"vision-language models\" OR abs:\"vision-language models\" OR ti:\"multimodal language model\" OR abs:\"multimodal language model\") AND (ti:\"post-training evaluation\" OR abs:\"post-training evaluation\" OR ti:\"alignment evaluation\" OR abs:\"alignment evaluation\" OR ti:\"reward model evaluation\" OR abs:\"reward model evaluation\" OR ti:\"post-training generalization\" OR abs:\"post-training generalization\")", dateModes: ['submitted', 'updated'] },
];
const expectedTermVariants = { 'language model':['language models'], 'large language model':['large language models'], llm:['llms'], 'vision-language model':['vision-language models','vision language model','vision language models'], 'multimodal language model':['multimodal language models'], 'post-training':['post training','posttraining'], 'supervised fine-tuning':['supervised finetuning','supervised fine tuning'], 'continual fine-tuning':['continual finetuning','continual fine tuning'], 'reward model':['reward models'], 'reward modeling':['reward modelling'], 'preference optimization':['preference optimisation'], 'policy optimization':['policy optimisation'], 'verifiable reward':['verifiable rewards'], 'parameter-efficient fine-tuning':['parameter efficient finetuning','parameter efficient fine tuning'] };
type CandidateDecision = ReturnType<typeof evaluateCandidate<PaperMetadata>>;
const positives: { track: string; title: string; aiTechnique: string; engineeringTask: string }[] = [
  { track: 'pt-foundations', title: 'A survey of language model post-training objectives', aiTechnique: 'language model', engineeringTask: 'post-training' },
  { track: 'pt-sft', title: 'Supervised fine-tuning of large language models', aiTechnique: 'large language model', engineeringTask: 'supervised fine-tuning' },
  { track: 'pt-data-curation', title: 'Instruction tuning data quality for language models', aiTechnique: 'language model', engineeringTask: 'instruction tuning' },
  { track: 'pt-synthetic-data', title: 'Synthetic instruction data for language models', aiTechnique: 'language model', engineeringTask: 'synthetic instruction' },
  { track: 'pt-reward-modeling', title: 'Process reward models for large language models', aiTechnique: 'large language model', engineeringTask: 'reward model' },
  { track: 'pt-preference-optimization', title: 'Direct preference optimization for LLMs', aiTechnique: 'llm', engineeringTask: 'preference optimization' },
  { track: 'pt-policy-optimization', title: 'GRPO optimization for large language models', aiTechnique: 'large language model', engineeringTask: 'grpo' },
  { track: 'pt-verifiable-rewards', title: 'Reinforcement learning with verifiable rewards for LLMs', aiTechnique: 'llm', engineeringTask: 'verifiable reward' },
  { track: 'pt-reasoning', title: 'Reasoning training for language models', aiTechnique: 'language model', engineeringTask: 'reasoning training' },
  { track: 'pt-distillation', title: 'Policy distillation for large language models', aiTechnique: 'large language model', engineeringTask: 'distillation' },
  { track: 'pt-tool-agent', title: 'Agent reinforcement learning for language models', aiTechnique: 'language model', engineeringTask: 'reinforcement learning' },
  { track: 'pt-multimodal', title: 'Instruction tuning for vision-language models', aiTechnique: 'vision-language model', engineeringTask: 'instruction tuning' },
  { track: 'pt-safety-alignment', title: 'Safety alignment of language models', aiTechnique: 'language model', engineeringTask: 'safety alignment' },
  { track: 'pt-adaptation', title: 'Continual fine-tuning of language models', aiTechnique: 'language model', engineeringTask: 'continual fine-tuning' },
  { track: 'pt-efficient-tuning', title: 'QLoRA for large language models', aiTechnique: 'large language model', engineeringTask: 'qlora' },
  { track: 'pt-training-systems', title: 'Asynchronous RLHF training of LLMs', aiTechnique: 'llm', engineeringTask: 'rlhf' },
  { track: 'pt-stability', title: 'Entropy collapse in language model post-training', aiTechnique: 'language model', engineeringTask: 'post-training' },
  { track: 'pt-evaluation', title: 'Evaluation of language model post-training generalization', aiTechnique: 'language model', engineeringTask: 'post-training' },
];

function paper(title: string, track = 'pt-foundations', extra: Partial<PaperMetadata> = {}): PaperMetadata {
  return {
    baseId: '2609.90001', arxivId: '2609.90001v1', version: 1,
    title, summary: '', authors: ['Synthetic Fixture'], categories: ['cs.CL'],
    published: '2026-09-01T00:00:00Z', updated: '2026-09-01T00:00:00Z',
    matchedTracks: [track], ...extra,
  };
}

const realRegressionFixtures: { name: string; paper: PaperMetadata; expected: { accepted: boolean; reasons: CandidateDecision['reasons']; signals: CandidateDecision['signals']; source: Required<Pick<PaperMetadata, 'authors' | 'categories' | 'published' | 'updated'>>; aiTechniques: string[]; engineeringTasks: string[]; eligibleTracks: string[]; primaryTrack: string | null } }[] = [
  {
    name: 'MedProb rejects a frozen VLM probe whose only task match was rejection sampling',
    paper: { baseId: '2609.04336', arxivId: '2609.04336v1', version: 1, title: 'MedProb: Probing Internal Representations of Vision-Language Models for Medical Question Answering', summary: 'Medical visual question answering (Med-VQA) is often assumed to require medical fine-tuning, large models, or complex multi-agent pipelines. We revisit this assumption with \\textbf{MedProb}, a lightweight probing framework that predicts multiple-choice Med-VQA answers from frozen VLM representations without free-text generation. Across PATH-VQA, SLAKE, and VQA-RAD, MedProb recovers substantially more answer-relevant signal than prompting and performs stronger than medical VLMs and agentic systems. Probing also reduces the apparent gap between small and large models compared to prompting, suggesting that smaller VLMs contain more recoverable Med-VQA signal than generation-based evaluation reveals. Across 14 matched general-purpose and medical VLM pairs, medical adaptation does not consistently improve this linear decodability. Finally, free-text generation exhibits an answer-position bias of up to 10 percentage points, whereas MedProb also has positional bias, however, it is impacted differently than prompting. Our main results target the multiple-choice/multiclass Med-VQA setting; we additionally show the probe can be extended to open-ended generation via a rejection-sampling scoring procedure.', authors: ['Erfan Nourbakhsh', 'Ke Yang', 'Anthony Rios'], categories: ['cs.CL'], published: '2026-09-03T18:04:36Z', updated: '2026-09-03T18:04:36Z', matchedTracks: ['pt-synthetic-data'] },
    expected: { accepted: false, reasons: { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: false, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: false, lane: 'ai' }, source: { authors: ['Erfan Nourbakhsh', 'Ke Yang', 'Anthony Rios'], categories: ['cs.CL'], published: '2026-09-03T18:04:36Z', updated: '2026-09-03T18:04:36Z' }, aiTechniques: ['language model', 'vision-language model'], engineeringTasks: [], eligibleTracks: [], primaryTrack: null },
  },
  {
    name: 'VLM videogame annotation is excluded while preserving multimodal RL signals',
    paper: { baseId: '2608.05949', arxivId: '2608.05949v1', version: 1, title: 'VLMs for Videogame Data Annotation', summary: 'Vision Language Models (VLMs) and Artificial Intelligence (AI) agents have revolutionized how engineers approach complex problems in real-world applications. Their adoption in video games is on the other hand limited by the extreme variability of the synthetic scenarios and their poor compliance with real-world physics. Here we investigate the use of VLMs for annotating video game frame sequences with reward signals, a task with several potential applications including, among others, conditioned training and offline reinforcement learning. We show that VLMs often struggle to answer basic questions on racing video games (although we observed a similar behavior on other game genres) and discuss countermeasures such as VLM output mixing and prompt optimization. We also show how input sequence length, resolution, and question batching affect the annotation quality and its token consumption.', authors: ['Katrin Schmid', 'Iuri Frosio'], categories: ['cs.AI', 'cs.CV', 'cs.LG'], published: '2026-08-06T12:20:53Z', updated: '2026-08-06T12:20:53Z', matchedTracks: ['pt-multimodal'] },
    expected: { accepted: false, reasons: { sourceAccepted: true, dateAccepted: true, excluded: true, technologyAccepted: true, taskAccepted: true, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: true, lane: 'ai' }, source: { authors: ['Katrin Schmid', 'Iuri Frosio'], categories: ['cs.AI', 'cs.CV', 'cs.LG'], published: '2026-08-06T12:20:53Z', updated: '2026-08-06T12:20:53Z' }, aiTechniques: ['language model', 'vision-language model'], engineeringTasks: ['reinforcement learning'], eligibleTracks: [], primaryTrack: null },
  },
  {
    name: 'post-training quantization remains an evaluator limitation after title-only discovery calibration',
    paper: { baseId: '2609.00049', arxivId: '2609.00049v1', version: 1, title: 'REAL-Q: E2E LLM Quantization via Dynamic Gradient Descent', summary: 'Post-training quantization (PTQ) is essential for deploying large language models (LLMs) under strict resource constraints. State-of-the-art PTQ methods quantize each layer with a single closed-form second-order solver: to remain analytically tractable, they heavily approximate the global loss (dropping cross-channel coupling, pooling output rows into groups), and they then freeze the resulting Hessian across the entire layer, with no way to refresh it as the loss landscape shifts column by column--a phenomenon we call information misalignment. We propose REAL-Q (Real-time E2E-loss Aligned LLM Quantization), a novel PTQ paradigm that breaks this compromise: instead of diluting the objective for the sake of analytic tractability, REAL-Q targets an end-to-end-aligned surrogate of the global loss and refines it via fine-grained, dynamic Block-wise Gradient Descent applied after every column block (128 columns). By coupling this fine-grained correction with a sliding window mechanism for smooth cross-layer transitions, REAL-Q effectively mitigates error propagation across the network. On LLaMA-3.1 (8B and 70B) and Qwen3 (0.6B-32B) at W4A16, REAL-Q reduces end-to-end KL divergence by up to ~49% relative to state-of-the-art globally-guided methods.', authors: ['Qian Zhang', 'Yaoming Li', 'Zhewen Tan', 'Yanshu Wang', 'Heng Lu', 'Kun Su', 'Zongwei Lv', 'Wenhan Yu', 'Yongge Ma', 'Yinjun Han', 'Ruikuang Liu', 'Tong Yang'], categories: ['cs.LG', 'cs.AI'], published: '2026-08-30T06:30:31Z', updated: '2026-08-30T06:30:31Z', matchedTracks: ['pt-foundations'] },
    expected: { accepted: true, reasons: { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: true, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: true, lane: 'ai' }, source: { authors: ['Qian Zhang', 'Yaoming Li', 'Zhewen Tan', 'Yanshu Wang', 'Heng Lu', 'Kun Su', 'Zongwei Lv', 'Wenhan Yu', 'Yongge Ma', 'Yinjun Han', 'Ruikuang Liu', 'Tong Yang'], categories: ['cs.LG', 'cs.AI'], published: '2026-08-30T06:30:31Z', updated: '2026-08-30T06:30:31Z' }, aiTechniques: ['language model', 'large language model', 'llm'], engineeringTasks: ['post-training'], eligibleTracks: ['pt-foundations'], primaryTrack: 'pt-foundations' },
  },
  {
    name: 'test-time rejection sampling has no model post-training task evidence',
    paper: { baseId: '2507.12399', arxivId: '2507.12399v3', version: 3, title: 'ROC-n-reroll: How verifier imperfection affects test-time scaling', summary: 'Test-time scaling aims to improve language model performance by leveraging additional compute during inference. Many works have empirically studied techniques such as Best-of-N (BoN) and Rejection Sampling (RS) that make use of a verifier to enable test-time scaling. However, to date there is little theoretical understanding of how verifier imperfection affects performance -- a gap we address in this work. Specifically, we prove that the instance-level accuracy of these methods is precisely characterized by the geometry of the verifier\'s ROC curve. Our theory has two important takeaways, confirmed by experiments with Qwen and LLama models on GSM8K and MATH500. First, RS outperforms BoN for fixed compute, while both methods converge to the same accuracy in the infinite-compute limit. Second, it is generally impossible to predict the high-compute performance of either method based on observations in the low-compute regime.', authors: ['Florian E. Dorner', 'Yatong Chen', 'André F. Cruz', 'Fanny Yang'], categories: ['cs.LG', 'stat.ML'], published: '2025-07-16T16:44:29Z', updated: '2026-08-17T15:56:15Z', matchedTracks: ['pt-synthetic-data'] },
    expected: { accepted: false, reasons: { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: false, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: false, lane: 'ai' }, source: { authors: ['Florian E. Dorner', 'Yatong Chen', 'André F. Cruz', 'Fanny Yang'], categories: ['cs.LG', 'stat.ML'], published: '2025-07-16T16:44:29Z', updated: '2026-08-17T15:56:15Z' }, aiTechniques: ['language model'], engineeringTasks: [], eligibleTracks: [], primaryTrack: null },
  },
  {
    name: 'an RLHF mention in a behavioral audit remains an evaluator limitation after title-only discovery calibration',
    paper: { baseId: '2606.11082', arxivId: '2606.11082v1', version: 1, title: 'The Shibboleth Effect: Auditing the Cross-Lingual Distributional Skew of Large Language Models', summary: 'This study investigates cross-lingual distributional skew (the Shibboleth Effect) in frontier large language models (LLMs) subjected to sustained adversarial conditions. We develop a multi-agent geopolitical wargame, the Cerulean Sea Crisis, a synthetic maritime territorial dispute designed to mirror the structural dynamics of Eastern Mediterranean conflicts. Six frontier models (GPT-4o, Llama-4, Mistral-Large, Gemini-3.1-Pro, Qwen3.6-Plus, and DeepSeek-R1) participate in a between-groups experiment (N = 10 games per arm, K = 5 rounds per game) in which the sole manipulation is the language of play (English versus Turkish), producing 586 validated statements. A zero-shot classifier assesses behavioral dispositions along two continuous dimensions: Concession Rate and Coercive Rhetoric. The results are heterogeneous. Llama-4 shows a substantial, Holm-corrected increase in coercive rhetoric under Turkish (delta = +0.800, p = .002), whereas Gemini-3.1-Pro displays an equally large decrease (delta = -0.750, p = .005). DeepSeek-R1 exhibits a similar negative shift (delta = -0.860, p = .006) and provides chain-of-thought evidence consistent with a buffering mechanism. GPT-4o shows no detectable effect (delta = +0.130, p = .614). These findings indicate that cross-lingual behavioral skew is contingent on model architecture and training regime rather than a universal property of Western-origin LLMs. We identify two distinct buffering mechanisms, chain-of-thought institutional anchoring and multilingual RLHF alignment, and discuss their implications for integrating LLMs safely into diplomatic and crisis-management settings.', authors: ['Hakan Mehmetcik'], categories: ['cs.CL', 'cs.CY'], published: '2026-06-09T16:42:00Z', updated: '2026-06-09T16:42:00Z', matchedTracks: ['pt-safety-alignment'] },
    expected: { accepted: true, reasons: { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: true, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: true, lane: 'ai' }, source: { authors: ['Hakan Mehmetcik'], categories: ['cs.CL', 'cs.CY'], published: '2026-06-09T16:42:00Z', updated: '2026-06-09T16:42:00Z' }, aiTechniques: ['language model', 'large language model', 'llm'], engineeringTasks: ['rlhf'], eligibleTracks: ['pt-safety-alignment'], primaryTrack: 'pt-safety-alignment' },
  },
  {
    name: 'encoder-only FinBERT LoRA remains an accepted boundary requiring human review',
    paper: { baseId: '2608.09834', arxivId: '2608.09834v1', version: 1, title: 'RA-FinBERT: Rule-aware LoRA adaptation for low-resource financial sentiment classification', summary: 'Financial sentiment analysis converts unstructured financial news into quantitative signals that can support market analysis and decision-making. Existing work on resource-efficient financial NLP has largely focused on compressing or adapting pretrained language models, with less attention to combining contextual representations with lightweight rule-derived features. This study develops Rule-Aware FinBERT (RA-FinBERT), a parameter-efficient framework that integrates low-rank adaptation (LoRA) with three continuous VADER-derived sentiment proportions (positive, negative, and neutral) and a source-level metadata feature. The standardized four-dimensional feature vector is directly concatenated with the 768-dimensional final-layer FinBERT [CLS] representation and passed through a lightweight classification head. This design introduces only 1,024 additional trainable weights relative to a structurally matched text-only FinBERT model. RA-FinBERT was evaluated against text-only FinBERT and a lightweight DistilBERT baseline for three-class sentiment classification of financial-news titles and descriptions. On the held-out test set, RA-FinBERT achieved 69.89% accuracy and a macro F1 score of 0.634, compared with 63.44% and 0.526 for text-only FinBERT. Neutral-class recall increased from 18.18% to 45.45%. The framework supports both CPU and GPU execution, offering a lightweight and practical approach to financial sentiment classification under constrained computational resources. These findings indicate that rule-derived sentiment information and source metadata can provide complementary signals to contextual FinBERT representations and improve performance with minimal additional model complexity.', authors: ['Fan Zhang', 'Jiaming Li'], categories: ['cs.CL', 'cs.LG'], published: '2026-08-10T16:52:19Z', updated: '2026-08-10T16:52:19Z', matchedTracks: ['pt-efficient-tuning'] },
    expected: { accepted: true, reasons: { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: true, trackAccepted: true }, signals: { technologyMatched: true, taskMatched: true, lane: 'ai' }, source: { authors: ['Fan Zhang', 'Jiaming Li'], categories: ['cs.CL', 'cs.LG'], published: '2026-08-10T16:52:19Z', updated: '2026-08-10T16:52:19Z' }, aiTechniques: ['language model'], engineeringTasks: ['lora'], eligibleTracks: ['pt-efficient-tuning'], primaryTrack: 'pt-efficient-tuning' },
  },
];

test('post-training loads the complete paper contract', () => withPostTrainingFixture(async root => {
  const { library } = loadEngineContext({ root, libraryId });
  if (library.kind !== 'paper') throw new Error('expected paper library');
  assert.equal(library.displayName, 'LLM Post-Training（大模型后训练知识库）');
  assert.equal(library.startDate, '2026-01-01'); assert.equal(library.paperPolicy.startDate, library.startDate);
  assert.equal(library.overlapHours, 48); assert.equal(library.downloadAfterHardFilter, true);
  assert.equal(library.currentTask.maxPapers, 180);
  assert.deepEqual(library.currentTask.trackLimits, Object.fromEntries(expectedTracks.map(id => [id, 10])));
  assert.deepEqual(library.tracks.map(track => track.id), expectedTracks);
  assert.deepEqual(library.tracks.map(track => ({ id: track.id, query: track.query, dateModes: track.dateModes })), expectedQueryContract);
  assert.deepEqual(library.paperPolicy.trackPriority, expectedTracks); assert.deepEqual(Object.keys(library.categories.tracks), expectedTracks);
  assert.equal(library.categories.fallbackPdf, '99-Unclassified'); assert.deepEqual(library.paperPolicy.programStructureTerms, []); assert.deepEqual(library.paperPolicy.excludedDomains, ['video game', 'videogame']);
  assert.deepEqual(library.paperPolicy.termVariants, expectedTermVariants);
  assert.ok(listLibraries(root).some(item => item.libraryId === libraryId));
  const names = ['library.yaml', 'query-matrix.yaml', 'paper-policy.yaml', 'categories.yaml'];
  assert.deepEqual((await readdir(join(root, 'config', libraryId))).sort(), [...names].sort());
  assert.deepEqual(configurationFiles(libraryId, 'paper').slice(-4), names.map(name => join(libraryId, name)));
  for (const mode of ['current', 'weekly']) { const plan = routeHarvestPlan(['--mode', mode, '--format', 'json'], { root, libraryId }); assert.equal(plan.trackCount, 18); assert.equal(plan.totalShards, 36); assert.equal(plan.submittedShards, 18); assert.equal(plan.updatedShards, 18); assert.equal(plan.maxPapers, mode === 'current' ? 180 : 18); }
  const schedule = routeScheduleConfig(['--format', 'json'], { root, libraryId }); assert.equal(schedule.enabled, true); assert.equal(schedule.taskName, 'paper-knowledge-engine-llm-post-training-weekly'); assert.deepEqual(schedule.command, ['--library', libraryId, 'run-task', '--mode', 'weekly']);
}));

test('post-training calibrates real false-positive samples without treating track labels as inclusion evidence', () => withPostTrainingFixture(async root => {
  const { library } = loadEngineContext({ root, libraryId });
  if (library.kind !== 'paper') throw new Error('expected paper library');
  for (const fixture of realRegressionFixtures) {
    const decision: CandidateDecision = evaluateCandidate(fixture.paper, library.paperPolicy);
    assert.equal(decision.accepted, fixture.expected.accepted, fixture.name);
    assert.deepEqual(decision.reasons, fixture.expected.reasons, fixture.name);
    assert.deepEqual(decision.signals, fixture.expected.signals, fixture.name);
    assert.equal(decision.primaryTrack, fixture.expected.primaryTrack, fixture.name);
    assert.deepEqual({
      arxivId: decision.paper.arxivId, title: decision.paper.title, summary: decision.paper.summary,
      authors: decision.paper.authors, categories: decision.paper.categories,
      published: decision.paper.published, updated: decision.paper.updated,
      matchedTracks: decision.paper.matchedTracks, aiTechniques: decision.paper.aiTechniques,
      engineeringTasks: decision.paper.engineeringTasks, eligibleTracks: decision.paper.eligibleTracks,
    }, {
      arxivId: fixture.paper.arxivId, title: fixture.paper.title, summary: fixture.paper.summary,
      authors: fixture.expected.source.authors, categories: fixture.expected.source.categories,
      published: fixture.expected.source.published, updated: fixture.expected.source.updated,
      matchedTracks: fixture.paper.matchedTracks, aiTechniques: fixture.expected.aiTechniques,
      engineeringTasks: fixture.expected.engineeringTasks, eligibleTracks: fixture.expected.eligibleTracks,
    }, fixture.name);
  }
}));

test('post-training accepts all intended policy themes', () => withPostTrainingFixture(async root => {
  const { library } = loadEngineContext({ root, libraryId });
  if (library.kind !== 'paper') throw new Error('expected paper library');
  for (const { track, title, aiTechnique, engineeringTask } of positives) {
    const decision: CandidateDecision = evaluateCandidate(paper(title, track), library.paperPolicy);
    assert.equal(decision.accepted, true, `${track}: ${JSON.stringify(decision.reasons)}`);
    assert.deepEqual(decision.reasons, { sourceAccepted: true, dateAccepted: true, excluded: false, technologyAccepted: true, taskAccepted: true, trackAccepted: true }, track);
    assert.deepEqual(decision.signals, { technologyMatched: true, taskMatched: true, lane: 'ai' }, track);
    assert.ok(decision.paper.aiTechniques.includes(aiTechnique), `${track}: missing ${aiTechnique}`);
    assert.ok(decision.paper.engineeringTasks.includes(engineeringTask), `${track}: missing ${engineeringTask}`);
    assert.deepEqual(decision.paper.eligibleTracks, [track], track);
    assert.equal(decision.primaryTrack, track);
  }
}));

test('post-training rejects lexical negatives and validates source/date/track', () => withPostTrainingFixture(async root => {
  const { library } = loadEngineContext({ root, libraryId });
  if (library.kind !== 'paper') throw new Error('expected paper library');
  const decide = (input: PaperMetadata) => evaluateCandidate(input, library.paperPolicy);
  for (const title of [
    'PPO reinforcement learning for robot locomotion',
    'GRPO for game agents without natural language processing',
    'Large language model pretraining data scaling',
    'Prompt optimization for language model question answering',
    'Language model inference acceleration with quantization',
    'Language model agent orchestration and message routing',
    'Fine-tuning a language model for a hospital application',
    'DPO for a scheduling solver',
  ]) assert.equal(decide(paper(title)).accepted, false, title);
  const title = 'Post-training of language models';
  assert.equal(decide(paper(title, 'pt-foundations', { arxivId: '2609.90001v2' })).reasons.sourceAccepted, false);
  assert.equal(decide(paper(title, 'unknown-track')).reasons.trackAccepted, false);
  assert.equal(decide(paper(title, 'pt-foundations', { published: '2025-01-01', updated: '2025-12-31' })).accepted, false);
  assert.equal(decide(paper(title, 'pt-foundations', { published: '2025-01-01', updated: '2026-01-01' })).accepted, true);
  assert.equal(decide(paper(title, 'pt-foundations', { published: '2026-01-01', updated: '2026-01-01' })).accepted, true);
  assert.equal(decide(paper(title, 'pt-foundations', { updated: 'invalid-date' })).accepted, false);
  assert.equal(decide(paper('An unrelated systems paper')).accepted, false);
  for (const title of [
    'POST–TRAINING of LLMs',
    'Reward modelling for language models',
    'Reward hacking in language model reinforcement learning',
    'Forgetting and jailbreaks after language model safety alignment',
  ]) assert.equal(decide(paper(title)).accepted, true, title);
  // A known limitation: source text mentioning related work can satisfy lexical gates.
  const ambiguous = paper('Language model inference study', 'pt-evaluation', {
    summary: 'Related work discusses GRPO, but our contribution is an inference cache.',
  });
  assert.equal(decide(ambiguous).accepted, true);
}));
